export const PACKAGE_STATUS = [
  "ORDER_CREATED",
  "PICKUP_REQUEST",
  "PICKUP_PROCESSING",
  "PICKUP_VERIFIED",
  "DELIVERY_PROCESSING",
  "DELIVERY_POSPONED",
  "DELIVERED",
  "DELIVERY_CANCELLED",
  "RETURN_TO_VENDOR",
  "RETURNED"
] as const;

export const PAYMENT_METHODS = [
  "NOT_PAID",
  "PAID_ONLINE",
  "PAID_BY_CASH",
  "PAID_THROUGH_BANK",
  "DIRECTLY_TO_VENDOR"
] as const;
